import { Language, MovieCertification, MovieStatus } from '../../constants/enums.js';

export interface SeedCast {
  name: string;
  role: string;
  profileUrl?: string;
}

export interface SeedCrew {
  name: string;
  job: string;
  profileUrl?: string;
}

export interface SeedMovie {
  title: string;
  description: string;
  genres: string[];
  duration: number;
  releaseDate: Date;
  language: Language;
  certification: MovieCertification;
  posterUrl: string;
  backdropUrl: string;
  rating: number;
  showStatus: MovieStatus;
  trailerUrl: string;
  cast: SeedCast[];
  crew: SeedCrew[];
  technicalSpecs?: string[];
  isTrending?: boolean;
}

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const poster = (title: string) => `https://picsum.photos/seed/${slug(title)}-poster/800/1200`;
const backdrop = (title: string) => `https://picsum.photos/seed/${slug(title)}-backdrop/1600/900`;
const profile = (name: string) => `https://picsum.photos/seed/${slug(name)}/400/400`;

const trailer = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ';

const movie = (m: Omit<SeedMovie, 'posterUrl' | 'backdropUrl' | 'trailerUrl'> & {
  cast: Array<Omit<SeedCast, 'profileUrl'>>;
  crew: Array<Omit<SeedCrew, 'profileUrl'>>;
}): SeedMovie => ({
  ...m,
  posterUrl: poster(m.title),
  backdropUrl: backdrop(m.title),
  trailerUrl: trailer,
  cast: m.cast.map((c) => ({ ...c, profileUrl: profile(c.name) })),
  crew: m.crew.map((c) => ({ ...c, profileUrl: profile(c.name) })),
  technicalSpecs: m.technicalSpecs || ['DOLBY ATMOS', '4K ULTRA HD', 'IMAX'],
  isTrending: m.isTrending ?? Math.random() > 0.7,
});

export const moviesData: SeedMovie[] = [
  // ─── MALAYALAM ────────────────────────────────────────────────────────────
  movie({
    title: 'Manjummel Boys',
    description: 'A group of friends on a trip to Kodaikanal face the unimaginable when one of them falls into the legendary Guna Caves.',
    genres: ['Survival', 'Thriller', 'Drama'],
    duration: 135,
    releaseDate: new Date('2024-02-22'),
    language: Language.MALAYALAM,
    certification: MovieCertification.UA,
    rating: 8.6,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Soubin Shahir', role: 'Kuttan' },
      { name: 'Sreenath Bhasi', role: 'Siju David' },
      { name: 'Balu Varghese', role: 'Prashant' },
    ],
    crew: [{ name: 'Chidambaram S. Poduval', job: 'Director' }],
  }),
  movie({
    title: '2018: Everyone is a Hero',
    description: 'The harrowing true story of ordinary Keralites who became heroes during the devastating 2018 floods.',
    genres: ['Drama', 'Survival', 'Thriller'],
    duration: 145,
    releaseDate: new Date('2023-05-05'),
    language: Language.MALAYALAM,
    certification: MovieCertification.UA,
    rating: 8.4,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Tovino Thomas', role: 'Anoop' },
      { name: 'Kunchacko Boban', role: 'Nixon' },
      { name: 'Asif Ali', role: 'Shaji' },
    ],
    crew: [{ name: 'Jude Anthany Joseph', job: 'Director' }],
  }),
  movie({
    title: 'Minnal Murali',
    description: 'A small-town tailor gains superpowers after being struck by lightning and must stop a vengeful villain who got the same gift.',
    genres: ['Superhero', 'Action', 'Fantasy'],
    duration: 159,
    releaseDate: new Date('2021-12-24'),
    language: Language.MALAYALAM,
    certification: MovieCertification.UA,
    rating: 8.1,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Tovino Thomas', role: 'Jaison / Minnal Murali' },
      { name: 'Guru Somasundaram', role: 'Shibu' },
    ],
    crew: [{ name: 'Basil Joseph', job: 'Director' }],
  }),
  movie({
    title: 'Kumbalangi Nights',
    description: 'Four dysfunctional brothers in a Kerala fishing village learn to reconcile their broken bonds and confront a toxic neighbour.',
    genres: ['Drama', 'Family'],
    duration: 135,
    releaseDate: new Date('2019-02-07'),
    language: Language.MALAYALAM,
    certification: MovieCertification.A,
    rating: 8.5,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Shane Nigam', role: 'Bobby' },
      { name: 'Soubin Shahir', role: 'Saji' },
      { name: 'Fahadh Faasil', role: 'Shammi' },
    ],
    crew: [{ name: 'Madhu C. Narayanan', job: 'Director' }],
  }),
  movie({
    title: 'Drishyam 2',
    description: 'Six years after the events of the first film, Georgekutty must again outsmart the police as the case is reopened.',
    genres: ['Thriller', 'Crime', 'Drama'],
    duration: 152,
    releaseDate: new Date('2021-02-19'),
    language: Language.MALAYALAM,
    certification: MovieCertification.UA,
    rating: 8.3,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Mohanlal', role: 'Georgekutty' },
      { name: 'Meena', role: 'Rani' },
    ],
    crew: [{ name: 'Jeethu Joseph', job: 'Director' }],
  }),
  movie({
    title: 'Lucifer',
    description: 'After the death of a powerful CM, a political vacuum erupts — and a mysterious figure steps out of the shadows.',
    genres: ['Action', 'Thriller', 'Political'],
    duration: 174,
    releaseDate: new Date('2019-03-28'),
    language: Language.MALAYALAM,
    certification: MovieCertification.UA,
    rating: 7.4,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Mohanlal', role: 'Stephen Nedumpally' },
      { name: 'Vivek Oberoi', role: 'Bobby' },
    ],
    crew: [{ name: 'Prithviraj Sukumaran', job: 'Director' }],
  }),
  movie({
    title: 'Premalu',
    description: 'A lighthearted romance unfolds when a Malayali graduate moves to Hyderabad chasing a dream and finds love along the way.',
    genres: ['Romance', 'Comedy'],
    duration: 156,
    releaseDate: new Date('2024-02-09'),
    language: Language.MALAYALAM,
    certification: MovieCertification.UA,
    rating: 8.2,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Naslen K. Gafoor', role: 'Sachin' },
      { name: 'Mamitha Baiju', role: 'Reenu' },
    ],
    crew: [{ name: 'Girish A. D.', job: 'Director' }],
  }),
  movie({
    title: 'RDX: Robert Dony Xavier',
    description: 'Three old friends with a violent past are forced to reunite when an attack on their families pulls them out of retirement.',
    genres: ['Action', 'Thriller'],
    duration: 150,
    releaseDate: new Date('2023-08-25'),
    language: Language.MALAYALAM,
    certification: MovieCertification.UA,
    rating: 7.9,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Shane Nigam', role: 'Xavier' },
      { name: 'Antony Varghese', role: 'Robert' },
      { name: 'Neeraj Madhav', role: 'Dony' },
    ],
    crew: [{ name: 'Nahas Hidhayath', job: 'Director' }],
  }),
  movie({
    title: 'Bramayugam',
    description: 'A fugitive singer stumbles upon a decaying mansion ruled by a sinister landlord — and the truth is far darker than myth.',
    genres: ['Horror', 'Fantasy', 'Period'],
    duration: 138,
    releaseDate: new Date('2024-02-15'),
    language: Language.MALAYALAM,
    certification: MovieCertification.A,
    rating: 8.1,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Mammootty', role: 'Kodumon Potti' },
      { name: 'Arjun Ashokan', role: 'Thevan' },
    ],
    crew: [{ name: 'Rahul Sadasivan', job: 'Director' }],
  }),
  movie({
    title: 'The Goat Life',
    description: 'Based on the bestselling novel Aadujeevitham, an Indian migrant is forced into brutal servitude in the Saudi desert.',
    genres: ['Drama', 'Survival'],
    duration: 173,
    releaseDate: new Date('2024-03-28'),
    language: Language.MALAYALAM,
    certification: MovieCertification.UA,
    rating: 8.0,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Prithviraj Sukumaran', role: 'Najeeb' },
      { name: 'Amala Paul', role: 'Sainu' },
    ],
    crew: [{ name: 'Blessy', job: 'Director' }],
  }),

  // ─── TAMIL ────────────────────────────────────────────────────────────────
  movie({
    title: 'Jailer',
    description: 'A retired jailer is pulled back into violence when his son goes missing while investigating a ruthless idol smuggler.',
    genres: ['Action', 'Crime', 'Thriller'],
    duration: 168,
    releaseDate: new Date('2023-08-10'),
    language: Language.TAMIL,
    certification: MovieCertification.UA,
    rating: 7.2,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Rajinikanth', role: 'Muthuvel Pandian' },
      { name: 'Mohanlal', role: 'Mathew' },
    ],
    crew: [{ name: 'Nelson Dilipkumar', job: 'Director' }],
  }),
  movie({
    title: 'Leo',
    description: 'A mild-mannered café owner in Theog is targeted by a crime syndicate who believe he is a notorious gangster from their past.',
    genres: ['Action', 'Thriller', 'Drama'],
    duration: 164,
    releaseDate: new Date('2023-10-19'),
    language: Language.TAMIL,
    certification: MovieCertification.UA,
    rating: 7.1,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Thalapathy Vijay', role: 'Parthiban / Leo' },
      { name: 'Sanjay Dutt', role: 'Antony Das' },
    ],
    crew: [{ name: 'Lokesh Kanagaraj', job: 'Director' }],
  }),
  movie({
    title: 'Vikram',
    description: 'A black-ops squad hunts a masked gang of vigilantes, only to uncover a conspiracy tied to a forgotten agent.',
    genres: ['Action', 'Thriller'],
    duration: 173,
    releaseDate: new Date('2022-06-03'),
    language: Language.TAMIL,
    certification: MovieCertification.UA,
    rating: 8.3,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Kamal Haasan', role: 'Vikram' },
      { name: 'Vijay Sethupathi', role: 'Sandhanam' },
      { name: 'Fahadh Faasil', role: 'Amar' },
    ],
    crew: [{ name: 'Lokesh Kanagaraj', job: 'Director' }],
  }),
  movie({
    title: 'Ponniyin Selvan: II',
    description: 'The Chola empire faces its greatest test as Arulmozhi Varman returns to claim his destiny in the conclusion of Kalki\'s epic.',
    genres: ['Historical', 'Epic', 'Drama'],
    duration: 169,
    releaseDate: new Date('2023-04-28'),
    language: Language.TAMIL,
    certification: MovieCertification.UA,
    rating: 7.9,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Vikram', role: 'Aditha Karikalan' },
      { name: 'Jayam Ravi', role: 'Arulmozhi Varman' },
      { name: 'Aishwarya Rai Bachchan', role: 'Nandini' },
    ],
    crew: [{ name: 'Mani Ratnam', job: 'Director' }],
  }),
  movie({
    title: 'Master',
    description: 'An alcoholic college professor is sent to reform a juvenile correctional facility run by a ruthless criminal.',
    genres: ['Action', 'Drama'],
    duration: 179,
    releaseDate: new Date('2021-01-13'),
    language: Language.TAMIL,
    certification: MovieCertification.UA,
    rating: 7.3,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Thalapathy Vijay', role: 'JD' },
      { name: 'Vijay Sethupathi', role: 'Bhavani' },
    ],
    crew: [{ name: 'Lokesh Kanagaraj', job: 'Director' }],
  }),
  movie({
    title: 'Kaithi',
    description: 'Over one brutal night, an ex-convict must drive a wounded officer\'s jeep through enemy territory to deliver a crucial witness.',
    genres: ['Action', 'Thriller'],
    duration: 145,
    releaseDate: new Date('2019-10-25'),
    language: Language.TAMIL,
    certification: MovieCertification.UA,
    rating: 8.5,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Karthi', role: 'Dilli' },
      { name: 'Narain', role: 'Bejoy' },
    ],
    crew: [{ name: 'Lokesh Kanagaraj', job: 'Director' }],
  }),
  movie({
    title: 'Asuran',
    description: 'A farmer and his sons are hunted by a powerful landlord family after a dispute over land turns deadly.',
    genres: ['Drama', 'Action'],
    duration: 147,
    releaseDate: new Date('2019-10-04'),
    language: Language.TAMIL,
    certification: MovieCertification.UA,
    rating: 8.4,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Dhanush', role: 'Sivasami' },
      { name: 'Manju Warrier', role: 'Pachaiyammal' },
    ],
    crew: [{ name: 'Vetrimaaran', job: 'Director' }],
  }),
  movie({
    title: '96',
    description: 'A travel photographer returns to his hometown school reunion and reconnects with his first love after twenty-two years.',
    genres: ['Romance', 'Drama'],
    duration: 158,
    releaseDate: new Date('2018-10-04'),
    language: Language.TAMIL,
    certification: MovieCertification.U,
    rating: 8.5,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Vijay Sethupathi', role: 'Ram' },
      { name: 'Trisha Krishnan', role: 'Jaanu' },
    ],
    crew: [{ name: 'C. Prem Kumar', job: 'Director' }],
  }),
  movie({
    title: 'Soorarai Pottru',
    description: 'A rural son of a school teacher defies the odds to build India\'s first low-cost airline for the common man.',
    genres: ['Drama', 'Biographical'],
    duration: 153,
    releaseDate: new Date('2020-11-12'),
    language: Language.TAMIL,
    certification: MovieCertification.UA,
    rating: 8.7,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Suriya', role: 'Nedumaaran Rajangam' },
      { name: 'Aparna Balamurali', role: 'Sundari' },
    ],
    crew: [{ name: 'Sudha Kongara', job: 'Director' }],
  }),
  movie({
    title: 'Maaveeran',
    description: 'A timid comic strip artist starts hearing the voice of his superhero character, urging him to stand up to a corrupt politician.',
    genres: ['Action', 'Fantasy', 'Comedy'],
    duration: 157,
    releaseDate: new Date('2023-07-14'),
    language: Language.TAMIL,
    certification: MovieCertification.UA,
    rating: 7.6,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Sivakarthikeyan', role: 'Sathya' },
      { name: 'Aditi Shankar', role: 'Nila' },
    ],
    crew: [{ name: 'Madonne Ashwin', job: 'Director' }],
  }),

  // ─── HINDI ────────────────────────────────────────────────────────────────
  movie({
    title: 'Jawan',
    description: 'A prison warden recruits a team of inmates to carry out a series of Robin Hood-style heists targeting corrupt elites.',
    genres: ['Action', 'Thriller'],
    duration: 169,
    releaseDate: new Date('2023-09-07'),
    language: Language.HINDI,
    certification: MovieCertification.UA,
    rating: 7.1,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Shah Rukh Khan', role: 'Vikram Rathore / Azad' },
      { name: 'Nayanthara', role: 'Narmada Rai' },
      { name: 'Vijay Sethupathi', role: 'Kaalie Gaikwad' },
    ],
    crew: [{ name: 'Atlee', job: 'Director' }],
  }),
  movie({
    title: 'Pathaan',
    description: 'An exiled RAW agent returns to stop a rogue ex-agent from unleashing a deadly bioweapon on India.',
    genres: ['Action', 'Spy', 'Thriller'],
    duration: 146,
    releaseDate: new Date('2023-01-25'),
    language: Language.HINDI,
    certification: MovieCertification.UA,
    rating: 6.0,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Shah Rukh Khan', role: 'Pathaan' },
      { name: 'Deepika Padukone', role: 'Rubina Mohsin' },
      { name: 'John Abraham', role: 'Jim' },
    ],
    crew: [{ name: 'Siddharth Anand', job: 'Director' }],
  }),
  movie({
    title: 'Animal',
    description: 'A son\'s obsessive love for his absent father spirals into violence when the family\'s empire comes under siege.',
    genres: ['Action', 'Crime', 'Drama'],
    duration: 201,
    releaseDate: new Date('2023-12-01'),
    language: Language.HINDI,
    certification: MovieCertification.A,
    rating: 6.4,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Ranbir Kapoor', role: 'Ranvijay Singh' },
      { name: 'Anil Kapoor', role: 'Balbir Singh' },
      { name: 'Bobby Deol', role: 'Abrar Haque' },
    ],
    crew: [{ name: 'Sandeep Reddy Vanga', job: 'Director' }],
  }),
  movie({
    title: '12th Fail',
    description: 'Based on a true story — a young man from a village in Chambal refuses to accept defeat on his path to becoming an IPS officer.',
    genres: ['Biographical', 'Drama'],
    duration: 147,
    releaseDate: new Date('2023-10-27'),
    language: Language.HINDI,
    certification: MovieCertification.U,
    rating: 9.2,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Vikrant Massey', role: 'Manoj Kumar Sharma' },
      { name: 'Medha Shankr', role: 'Shraddha Joshi' },
    ],
    crew: [{ name: 'Vidhu Vinod Chopra', job: 'Director' }],
  }),
  movie({
    title: 'Laapataa Ladies',
    description: 'Two young brides get accidentally swapped on a train ride home, setting off a charming journey of self-discovery.',
    genres: ['Comedy', 'Drama'],
    duration: 124,
    releaseDate: new Date('2024-03-01'),
    language: Language.HINDI,
    certification: MovieCertification.U,
    rating: 8.3,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Nitanshi Goel', role: 'Phool Kumari' },
      { name: 'Pratibha Ranta', role: 'Jaya' },
      { name: 'Ravi Kishan', role: 'Inspector Shyam Manohar' },
    ],
    crew: [{ name: 'Kiran Rao', job: 'Director' }],
  }),
  movie({
    title: 'Dangal',
    description: 'A former wrestler defies village tradition to train his two daughters to become world-class wrestlers for India.',
    genres: ['Biographical', 'Sports', 'Drama'],
    duration: 161,
    releaseDate: new Date('2016-12-23'),
    language: Language.HINDI,
    certification: MovieCertification.U,
    rating: 8.4,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Aamir Khan', role: 'Mahavir Singh Phogat' },
      { name: 'Fatima Sana Shaikh', role: 'Geeta Phogat' },
    ],
    crew: [{ name: 'Nitesh Tiwari', job: 'Director' }],
  }),
  movie({
    title: 'Andhadhun',
    description: 'A blind pianist becomes the unwilling witness to a murder, and his neat little world unravels in unexpected directions.',
    genres: ['Thriller', 'Crime', 'Dark Comedy'],
    duration: 139,
    releaseDate: new Date('2018-10-05'),
    language: Language.HINDI,
    certification: MovieCertification.A,
    rating: 8.2,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Ayushmann Khurrana', role: 'Akash' },
      { name: 'Tabu', role: 'Simi' },
      { name: 'Radhika Apte', role: 'Sophie' },
    ],
    crew: [{ name: 'Sriram Raghavan', job: 'Director' }],
  }),
  movie({
    title: 'Zindagi Na Milegi Dobara',
    description: 'Three friends take a bachelor road trip across Spain that changes their lives forever.',
    genres: ['Drama', 'Comedy', 'Adventure'],
    duration: 155,
    releaseDate: new Date('2011-07-15'),
    language: Language.HINDI,
    certification: MovieCertification.U,
    rating: 8.1,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Hrithik Roshan', role: 'Arjun' },
      { name: 'Farhan Akhtar', role: 'Imraan' },
      { name: 'Abhay Deol', role: 'Kabir' },
    ],
    crew: [{ name: 'Zoya Akhtar', job: 'Director' }],
  }),
  movie({
    title: 'Gully Boy',
    description: 'A street rapper from the Mumbai slums fights against all odds to make his voice heard in the Indian hip-hop scene.',
    genres: ['Musical', 'Drama'],
    duration: 153,
    releaseDate: new Date('2019-02-14'),
    language: Language.HINDI,
    certification: MovieCertification.UA,
    rating: 7.9,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Ranveer Singh', role: 'Murad' },
      { name: 'Alia Bhatt', role: 'Safeena' },
    ],
    crew: [{ name: 'Zoya Akhtar', job: 'Director' }],
  }),
  movie({
    title: '3 Idiots',
    description: 'Two friends search for their long-lost college buddy while reliving the hilarious chaos of their engineering days.',
    genres: ['Comedy', 'Drama'],
    duration: 170,
    releaseDate: new Date('2009-12-25'),
    language: Language.HINDI,
    certification: MovieCertification.U,
    rating: 8.4,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Aamir Khan', role: 'Rancho' },
      { name: 'R. Madhavan', role: 'Farhan' },
      { name: 'Sharman Joshi', role: 'Raju' },
    ],
    crew: [{ name: 'Rajkumar Hirani', job: 'Director' }],
  }),

  // ─── TELUGU ───────────────────────────────────────────────────────────────
  movie({
    title: 'RRR',
    description: 'Two legendary Indian revolutionaries bond in disguise before destiny forces them onto opposite sides of a brutal colonial war.',
    genres: ['Action', 'Historical', 'Epic'],
    duration: 187,
    releaseDate: new Date('2022-03-25'),
    language: Language.TELUGU,
    certification: MovieCertification.UA,
    rating: 7.9,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'N. T. Rama Rao Jr.', role: 'Komaram Bheem' },
      { name: 'Ram Charan', role: 'Alluri Sitarama Raju' },
    ],
    crew: [{ name: 'S. S. Rajamouli', job: 'Director' }],
  }),
  movie({
    title: 'Pushpa: The Rise',
    description: 'A cunning coolie rises through the ranks of a ruthless red sandalwood smuggling syndicate in the forests of Seshachalam.',
    genres: ['Action', 'Crime', 'Drama'],
    duration: 179,
    releaseDate: new Date('2021-12-17'),
    language: Language.TELUGU,
    certification: MovieCertification.UA,
    rating: 7.6,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Allu Arjun', role: 'Pushpa Raj' },
      { name: 'Fahadh Faasil', role: 'SP Bhanwar Singh Shekhawat' },
    ],
    crew: [{ name: 'Sukumar', job: 'Director' }],
  }),
  movie({
    title: 'Baahubali 2: The Conclusion',
    description: 'The reason Kattappa killed Baahubali is finally revealed as the epic saga of Mahishmati reaches its climax.',
    genres: ['Action', 'Epic', 'Fantasy'],
    duration: 167,
    releaseDate: new Date('2017-04-28'),
    language: Language.TELUGU,
    certification: MovieCertification.UA,
    rating: 8.2,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Prabhas', role: 'Amarendra Baahubali' },
      { name: 'Rana Daggubati', role: 'Bhallaladeva' },
      { name: 'Anushka Shetty', role: 'Devasena' },
    ],
    crew: [{ name: 'S. S. Rajamouli', job: 'Director' }],
  }),
  movie({
    title: 'HanuMan',
    description: 'A small village thief is gifted divine strength by Lord Hanuman to protect his people from a power-hungry tyrant.',
    genres: ['Superhero', 'Fantasy', 'Action'],
    duration: 158,
    releaseDate: new Date('2024-01-12'),
    language: Language.TELUGU,
    certification: MovieCertification.UA,
    rating: 8.0,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Teja Sajja', role: 'Hanumanthu' },
      { name: 'Amritha Aiyer', role: 'Meenakshi' },
    ],
    crew: [{ name: 'Prasanth Varma', job: 'Director' }],
  }),
  movie({
    title: 'Salaar: Part 1 — Ceasefire',
    description: 'A ruthless gangster must honour a childhood promise and protect his best friend from a city divided by violent warlords.',
    genres: ['Action', 'Crime', 'Drama'],
    duration: 175,
    releaseDate: new Date('2023-12-22'),
    language: Language.TELUGU,
    certification: MovieCertification.UA,
    rating: 6.6,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Prabhas', role: 'Deva / Salaar' },
      { name: 'Prithviraj Sukumaran', role: 'Vardharaja Mannar' },
    ],
    crew: [{ name: 'Prashanth Neel', job: 'Director' }],
  }),

  // ─── KANNADA ──────────────────────────────────────────────────────────────
  movie({
    title: 'KGF: Chapter 2',
    description: 'Rocky\'s blood-soaked rise to the top of the Kolar gold mines draws the attention of the Indian Prime Minister herself.',
    genres: ['Action', 'Crime', 'Period'],
    duration: 168,
    releaseDate: new Date('2022-04-14'),
    language: Language.KANNADA,
    certification: MovieCertification.UA,
    rating: 8.2,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Yash', role: 'Rocky' },
      { name: 'Sanjay Dutt', role: 'Adheera' },
      { name: 'Raveena Tandon', role: 'Ramika Sen' },
    ],
    crew: [{ name: 'Prashanth Neel', job: 'Director' }],
  }),
  movie({
    title: 'Kantara',
    description: 'A village ritual performer finds himself at the centre of a clash between tradition, faith and modern forest authorities.',
    genres: ['Folklore', 'Action', 'Drama'],
    duration: 150,
    releaseDate: new Date('2022-09-30'),
    language: Language.KANNADA,
    certification: MovieCertification.UA,
    rating: 8.2,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Rishab Shetty', role: 'Shiva' },
      { name: 'Sapthami Gowda', role: 'Leela' },
    ],
    crew: [{ name: 'Rishab Shetty', job: 'Director' }],
  }),
  movie({
    title: '777 Charlie',
    description: 'A lonely factory worker\'s life is turned upside down when a stray Labrador arrives at his doorstep.',
    genres: ['Drama', 'Adventure', 'Family'],
    duration: 164,
    releaseDate: new Date('2022-06-10'),
    language: Language.KANNADA,
    certification: MovieCertification.U,
    rating: 8.8,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Rakshit Shetty', role: 'Dharma' },
      { name: 'Sangeetha Sringeri', role: 'Devika' },
    ],
    crew: [{ name: 'Kiranraj K.', job: 'Director' }],
  }),

  // ─── ENGLISH ──────────────────────────────────────────────────────────────
  movie({
    title: 'Oppenheimer',
    description: 'The story of J. Robert Oppenheimer and the Manhattan Project\'s race to build the atomic bomb — and the aftermath that haunted him.',
    genres: ['Biographical', 'Drama', 'Historical'],
    duration: 180,
    releaseDate: new Date('2023-07-21'),
    language: Language.ENGLISH,
    certification: MovieCertification.UA,
    rating: 8.3,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Cillian Murphy', role: 'J. Robert Oppenheimer' },
      { name: 'Emily Blunt', role: 'Katherine Oppenheimer' },
      { name: 'Robert Downey Jr.', role: 'Lewis Strauss' },
    ],
    crew: [{ name: 'Christopher Nolan', job: 'Director' }],
  }),
  movie({
    title: 'Dune: Part Two',
    description: 'Paul Atreides unites with the Fremen to wage war against the conspirators who destroyed his family.',
    genres: ['Sci-Fi', 'Epic', 'Adventure'],
    duration: 166,
    releaseDate: new Date('2024-03-01'),
    language: Language.ENGLISH,
    certification: MovieCertification.UA,
    rating: 8.5,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Timothée Chalamet', role: 'Paul Atreides' },
      { name: 'Zendaya', role: 'Chani' },
      { name: 'Austin Butler', role: 'Feyd-Rautha' },
    ],
    crew: [{ name: 'Denis Villeneuve', job: 'Director' }],
  }),
  movie({
    title: 'Barbie',
    description: 'Barbie and Ken embark on a colourful journey of self-discovery after leaving the idyllic Barbieland for the real world.',
    genres: ['Comedy', 'Fantasy', 'Adventure'],
    duration: 114,
    releaseDate: new Date('2023-07-21'),
    language: Language.ENGLISH,
    certification: MovieCertification.UA,
    rating: 6.8,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Margot Robbie', role: 'Barbie' },
      { name: 'Ryan Gosling', role: 'Ken' },
    ],
    crew: [{ name: 'Greta Gerwig', job: 'Director' }],
  }),
  movie({
    title: 'Mission: Impossible — Dead Reckoning Part One',
    description: 'Ethan Hunt and the IMF team must track down a terrifying new weapon before it falls into the wrong hands.',
    genres: ['Action', 'Spy', 'Thriller'],
    duration: 163,
    releaseDate: new Date('2023-07-12'),
    language: Language.ENGLISH,
    certification: MovieCertification.UA,
    rating: 7.7,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Tom Cruise', role: 'Ethan Hunt' },
      { name: 'Hayley Atwell', role: 'Grace' },
    ],
    crew: [{ name: 'Christopher McQuarrie', job: 'Director' }],
  }),
  movie({
    title: 'Spider-Man: Across the Spider-Verse',
    description: 'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its existence.',
    genres: ['Animation', 'Action', 'Superhero'],
    duration: 140,
    releaseDate: new Date('2023-06-02'),
    language: Language.ENGLISH,
    certification: MovieCertification.U,
    rating: 8.6,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Shameik Moore', role: 'Miles Morales (voice)' },
      { name: 'Hailee Steinfeld', role: 'Gwen Stacy (voice)' },
    ],
    crew: [{ name: 'Joaquim Dos Santos', job: 'Director' }],
  }),
  movie({
    title: 'John Wick: Chapter 4',
    description: 'John Wick uncovers a path to defeating the High Table, but must face a deadly new enemy before he can earn his freedom.',
    genres: ['Action', 'Thriller', 'Crime'],
    duration: 169,
    releaseDate: new Date('2023-03-24'),
    language: Language.ENGLISH,
    certification: MovieCertification.A,
    rating: 7.7,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Keanu Reeves', role: 'John Wick' },
      { name: 'Donnie Yen', role: 'Caine' },
    ],
    crew: [{ name: 'Chad Stahelski', job: 'Director' }],
  }),
  movie({
    title: 'The Batman',
    description: 'In his second year fighting crime, Batman uncovers corruption in Gotham and confronts the Riddler, a sadistic killer with a mask.',
    genres: ['Action', 'Crime', 'Drama'],
    duration: 176,
    releaseDate: new Date('2022-03-04'),
    language: Language.ENGLISH,
    certification: MovieCertification.UA,
    rating: 7.8,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Robert Pattinson', role: 'Bruce Wayne / Batman' },
      { name: 'Zoë Kravitz', role: 'Selina Kyle' },
      { name: 'Paul Dano', role: 'The Riddler' },
    ],
    crew: [{ name: 'Matt Reeves', job: 'Director' }],
  }),
  movie({
    title: 'Interstellar',
    description: 'A team of explorers travel through a wormhole in space in a desperate attempt to ensure humanity\'s survival.',
    genres: ['Sci-Fi', 'Drama', 'Adventure'],
    duration: 169,
    releaseDate: new Date('2014-11-07'),
    language: Language.ENGLISH,
    certification: MovieCertification.UA,
    rating: 8.7,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Matthew McConaughey', role: 'Cooper' },
      { name: 'Anne Hathaway', role: 'Dr. Brand' },
      { name: 'Jessica Chastain', role: 'Murph' },
    ],
    crew: [{ name: 'Christopher Nolan', job: 'Director' }],
  }),
  movie({
    title: 'Inception',
    description: 'A thief who enters the dreams of others to steal secrets is offered a chance to have his old life back if he can plant an idea instead.',
    genres: ['Sci-Fi', 'Action', 'Thriller'],
    duration: 148,
    releaseDate: new Date('2010-07-16'),
    language: Language.ENGLISH,
    certification: MovieCertification.UA,
    rating: 8.8,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Leonardo DiCaprio', role: 'Cobb' },
      { name: 'Joseph Gordon-Levitt', role: 'Arthur' },
    ],
    crew: [{ name: 'Christopher Nolan', job: 'Director' }],
  }),
  movie({
    title: 'Avatar: The Way of Water',
    description: 'Jake Sully and Neytiri must protect their family when an ancient threat from their past returns to Pandora.',
    genres: ['Sci-Fi', 'Adventure', 'Epic'],
    duration: 192,
    releaseDate: new Date('2022-12-16'),
    language: Language.ENGLISH,
    certification: MovieCertification.UA,
    rating: 7.6,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Sam Worthington', role: 'Jake Sully' },
      { name: 'Zoe Saldaña', role: 'Neytiri' },
    ],
    crew: [{ name: 'James Cameron', job: 'Director' }],
  }),
  movie({
    title: 'Top Gun: Maverick',
    description: 'After more than thirty years of service, Maverick is pushed back into action to train a new generation of Top Gun pilots.',
    genres: ['Action', 'Drama'],
    duration: 130,
    releaseDate: new Date('2022-05-27'),
    language: Language.ENGLISH,
    certification: MovieCertification.UA,
    rating: 8.3,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Tom Cruise', role: 'Pete "Maverick" Mitchell' },
      { name: 'Miles Teller', role: 'Bradley "Rooster" Bradshaw' },
    ],
    crew: [{ name: 'Joseph Kosinski', job: 'Director' }],
  }),
  movie({
    title: 'Everything Everywhere All at Once',
    description: 'A Chinese-American laundromat owner is swept into a wild multiversal adventure to save the fabric of reality.',
    genres: ['Sci-Fi', 'Comedy', 'Drama'],
    duration: 139,
    releaseDate: new Date('2022-04-08'),
    language: Language.ENGLISH,
    certification: MovieCertification.A,
    rating: 7.8,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Michelle Yeoh', role: 'Evelyn Wang' },
      { name: 'Ke Huy Quan', role: 'Waymond Wang' },
    ],
    crew: [{ name: 'Daniels', job: 'Directors' }],
  }),
  movie({
    title: 'Guardians of the Galaxy Vol. 3',
    description: 'Peter Quill rallies his team around him to defend the universe and one of their own in a final goodbye.',
    genres: ['Action', 'Superhero', 'Sci-Fi'],
    duration: 150,
    releaseDate: new Date('2023-05-05'),
    language: Language.ENGLISH,
    certification: MovieCertification.UA,
    rating: 7.9,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Chris Pratt', role: 'Peter Quill / Star-Lord' },
      { name: 'Zoe Saldaña', role: 'Gamora' },
    ],
    crew: [{ name: 'James Gunn', job: 'Director' }],
  }),

  // ─── JAPANESE / KOREAN ────────────────────────────────────────────────────
  movie({
    title: 'Suzume',
    description: 'A teenage girl on Kyushu stumbles upon a mysterious door that sets her on a journey to close disaster portals across Japan.',
    genres: ['Animation', 'Fantasy', 'Adventure'],
    duration: 122,
    releaseDate: new Date('2022-11-11'),
    language: Language.JAPANESE,
    certification: MovieCertification.U,
    rating: 7.7,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Nanoka Hara', role: 'Suzume Iwato (voice)' },
      { name: 'Hokuto Matsumura', role: 'Souta Munakata (voice)' },
    ],
    crew: [{ name: 'Makoto Shinkai', job: 'Director' }],
  }),
  movie({
    title: 'Demon Slayer: Kimetsu no Yaiba — Mugen Train',
    description: 'Tanjiro and his companions board the Mugen Train to investigate a string of demonic disappearances.',
    genres: ['Animation', 'Action', 'Fantasy'],
    duration: 117,
    releaseDate: new Date('2020-10-16'),
    language: Language.JAPANESE,
    certification: MovieCertification.UA,
    rating: 8.2,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Natsuki Hanae', role: 'Tanjiro Kamado (voice)' },
      { name: 'Akari Kitō', role: 'Nezuko Kamado (voice)' },
    ],
    crew: [{ name: 'Haruo Sotozaki', job: 'Director' }],
  }),
  movie({
    title: 'Parasite',
    description: 'A poor family schemes to become employed by a wealthy family, only for their plan to spiral into something darker.',
    genres: ['Thriller', 'Dark Comedy', 'Drama'],
    duration: 132,
    releaseDate: new Date('2019-05-30'),
    language: Language.KOREAN,
    certification: MovieCertification.A,
    rating: 8.5,
    showStatus: MovieStatus.NOW_SHOWING,
    cast: [
      { name: 'Song Kang-ho', role: 'Ki-taek' },
      { name: 'Lee Sun-kyun', role: 'Park Dong-ik' },
    ],
    crew: [{ name: 'Bong Joon-ho', job: 'Director' }],
  }),

  // ─── UPCOMING ─────────────────────────────────────────────────────────────
  movie({
    title: 'Devara: Part 1',
    description: 'In a coastal village, a fearless protector stands guard over his people against smugglers who threaten their way of life.',
    genres: ['Action', 'Drama'],
    duration: 176,
    releaseDate: new Date('2026-09-27'),
    language: Language.TELUGU,
    certification: MovieCertification.UA,
    rating: 0,
    showStatus: MovieStatus.UPCOMING,
    cast: [
      { name: 'N. T. Rama Rao Jr.', role: 'Devara' },
      { name: 'Saif Ali Khan', role: 'Bhaira' },
      { name: 'Janhvi Kapoor', role: 'Thangam' },
    ],
    crew: [{ name: 'Koratala Siva', job: 'Director' }],
  }),
  movie({
    title: 'Pushpa 2: The Rule',
    description: 'Pushpa Raj returns to the forests as his war with the police and rival syndicates reaches its violent climax.',
    genres: ['Action', 'Crime'],
    duration: 185,
    releaseDate: new Date('2026-12-05'),
    language: Language.TELUGU,
    certification: MovieCertification.UA,
    rating: 0,
    showStatus: MovieStatus.UPCOMING,
    cast: [
      { name: 'Allu Arjun', role: 'Pushpa Raj' },
      { name: 'Rashmika Mandanna', role: 'Srivalli' },
      { name: 'Fahadh Faasil', role: 'SP Bhanwar Singh' },
    ],
    crew: [{ name: 'Sukumar', job: 'Director' }],
  }),
  movie({
    title: 'Thangalaan',
    description: 'A tribal leader in Kolar leads his clan in a desperate search for gold as colonial forces close in on their land.',
    genres: ['Historical', 'Action', 'Drama'],
    duration: 155,
    releaseDate: new Date('2026-08-15'),
    language: Language.TAMIL,
    certification: MovieCertification.UA,
    rating: 0,
    showStatus: MovieStatus.UPCOMING,
    cast: [
      { name: 'Vikram', role: 'Thangalaan' },
      { name: 'Parvathy Thiruvothu', role: 'Gengamma' },
    ],
    crew: [{ name: 'Pa. Ranjith', job: 'Director' }],
  }),
  movie({
    title: 'Kalki 2898 AD',
    description: 'A sci-fi epic set in a dystopian future inspired by Hindu mythology, where a mysterious warrior rises against a cruel regime.',
    genres: ['Sci-Fi', 'Mythological', 'Epic'],
    duration: 181,
    releaseDate: new Date('2026-06-27'),
    language: Language.TELUGU,
    certification: MovieCertification.UA,
    rating: 0,
    showStatus: MovieStatus.UPCOMING,
    cast: [
      { name: 'Prabhas', role: 'Bhairava' },
      { name: 'Amitabh Bachchan', role: 'Ashwatthama' },
      { name: 'Deepika Padukone', role: 'SUM-80 / Sumathi' },
    ],
    crew: [{ name: 'Nag Ashwin', job: 'Director' }],
  }),
  movie({
    title: 'Aavesham',
    description: 'Three college freshers in Bangalore befriend an eccentric local gangster to settle a score — and chaos unfolds.',
    genres: ['Comedy', 'Action', 'Drama'],
    duration: 158,
    releaseDate: new Date('2026-04-11'),
    language: Language.MALAYALAM,
    certification: MovieCertification.UA,
    rating: 0,
    showStatus: MovieStatus.UPCOMING,
    cast: [
      { name: 'Fahadh Faasil', role: 'Ranga' },
      { name: 'Sajin Gopu', role: 'Ambaan' },
    ],
    crew: [{ name: 'Jithu Madhavan', job: 'Director' }],
  }),
  movie({
    title: 'Joker: Folie à Deux',
    description: 'Arthur Fleck faces trial for his crimes as the Joker, and finds an unexpected soulmate in a fellow Arkham patient.',
    genres: ['Crime', 'Drama', 'Musical'],
    duration: 138,
    releaseDate: new Date('2026-10-04'),
    language: Language.ENGLISH,
    certification: MovieCertification.A,
    rating: 0,
    showStatus: MovieStatus.UPCOMING,
    cast: [
      { name: 'Joaquin Phoenix', role: 'Arthur Fleck / Joker' },
      { name: 'Lady Gaga', role: 'Lee Quinzel' },
    ],
    crew: [{ name: 'Todd Phillips', job: 'Director' }],
  }),
];
