import { UserRole, AuthProvider } from '../../constants/enums.js';
import type { IUser } from '../../interfaces/models.interface.js';

const avatar = (seed: string) => `https://i.pravatar.cc/300?u=${seed}`;
const cover  = (seed: string) => `https://picsum.photos/seed/${seed}-cover/1600/500`;

/**
 * Seed user records. `password` is intentionally omitted — the seeder
 * hashes a shared dev password and overlays it on every row so this file
 * never contains secrets.
 */
export const usersSeedData: Partial<IUser>[] = [
  // ── Admin ────────────────────────────────────────────────────────────────
  {
    name: 'Super Admin',
    username: 'admin_elite',
    email: 'admin@cinemaconnect.com',
    role: UserRole.ADMIN,
    authProvider: AuthProvider.LOCAL,
    avatar: avatar('admin_elite'),
    coverImageUrl: cover('admin_elite'),
    bio: 'Keeping the lights on at #CinemaConnect. Ping @grand_owner for theatre ops.',
    location: 'Mumbai, India',
    pronouns: 'they/them',
    website: 'https://cinemaconnect.com',
    socialLinks: [{ platform: 'twitter', url: 'https://twitter.com/cinemaconnect' }],
  },

  // ── Theatre Owner ────────────────────────────────────────────────────────
  {
    name: 'Theatre Owner',
    username: 'grand_owner',
    email: 'owner@cinemaconnect.com',
    role: UserRole.THEATRE_OWNER,
    authProvider: AuthProvider.LOCAL,
    avatar: avatar('grand_owner'),
    coverImageUrl: cover('grand_owner'),
    bio: 'Running a few good screens across South India. Big fan of #IMAX and real film prints.',
    location: 'Chennai, India',
  },

  // ── Regular Users ────────────────────────────────────────────────────────
  {
    name: 'John Doe',
    username: 'john_movie_fan',
    email: 'john@example.com',
    role: UserRole.USER,
    authProvider: AuthProvider.LOCAL,
    avatar: avatar('john_movie_fan'),
    coverImageUrl: cover('john_movie_fan'),
    bio: 'Movie junkie. Weekly reviewer. Prefers #Malayalam thrillers and #sci-fi. Say hi @jane_critic',
    location: 'Kochi, India',
    pronouns: 'he/him',
    website: 'https://letterboxd.com/johnmoviefan',
    socialLinks: [
      { platform: 'letterboxd', url: 'https://letterboxd.com/johnmoviefan' },
      { platform: 'twitter',    url: 'https://twitter.com/johnmoviefan' },
    ],
  },
  {
    name: 'Jane Smith',
    username: 'jane_critic',
    email: 'jane@example.com',
    role: UserRole.USER,
    authProvider: AuthProvider.LOCAL,
    avatar: avatar('jane_critic'),
    coverImageUrl: cover('jane_critic'),
    bio: 'Critic. Essay writer. I believe #drama is where cinema lives. Also see @john_movie_fan',
    location: 'Bengaluru, India',
    pronouns: 'she/her',
    website: 'https://example.com/jane',
  },
  {
    name: 'Mike Ross',
    username: 'mike_cpt',
    email: 'mike@example.com',
    role: UserRole.USER,
    authProvider: AuthProvider.LOCAL,
    avatar: avatar('mike_cpt'),
    coverImageUrl: cover('mike_cpt'),
    bio: 'Sunday afternoon moviegoer. #action #thriller #bollywood',
    location: 'Delhi, India',
  },
  {
    name: 'Priya Sharma',
    username: 'priya_cinephile',
    email: 'priya@example.com',
    role: UserRole.USER,
    authProvider: AuthProvider.LOCAL,
    avatar: avatar('priya_cinephile'),
    coverImageUrl: cover('priya_cinephile'),
    bio: 'Film student at FTII. Obsessed with #arthouse and world cinema. Huge Satyajit Ray fan.',
    location: 'Pune, India',
    pronouns: 'she/her',
    website: 'https://priyawrites.blog',
    socialLinks: [{ platform: 'instagram', url: 'https://instagram.com/priya_cinephile' }],
  },
  {
    name: 'Arjun Nair',
    username: 'arjun_reviews',
    email: 'arjun@example.com',
    role: UserRole.USER,
    authProvider: AuthProvider.LOCAL,
    avatar: avatar('arjun_reviews'),
    coverImageUrl: cover('arjun_reviews'),
    bio: 'Tech by day, movie reviews by night. #scifi #thriller #marvel addict.',
    location: 'Hyderabad, India',
    pronouns: 'he/him',
  },
  {
    name: 'Sneha Reddy',
    username: 'sneha_films',
    email: 'sneha@example.com',
    role: UserRole.USER,
    authProvider: AuthProvider.LOCAL,
    avatar: avatar('sneha_films'),
    coverImageUrl: cover('sneha_films'),
    bio: 'Telugu cinema enthusiast. RRR changed my life. Also into #korean dramas.',
    location: 'Vizag, India',
    socialLinks: [{ platform: 'twitter', url: 'https://twitter.com/sneha_films' }],
  },
  {
    name: 'Rahul Verma',
    username: 'rahul_binge',
    email: 'rahul@example.com',
    role: UserRole.USER,
    authProvider: AuthProvider.LOCAL,
    avatar: avatar('rahul_binge'),
    coverImageUrl: cover('rahul_binge'),
    bio: 'Binge watcher. I rate movies on vibes, not technicality. Hot takes only. #bollywood #comedy',
    location: 'Jaipur, India',
    pronouns: 'he/him',
  },
  {
    name: 'Ananya Gupta',
    username: 'ananya_movie_buff',
    email: 'ananya@example.com',
    role: UserRole.USER,
    authProvider: AuthProvider.LOCAL,
    avatar: avatar('ananya_movie_buff'),
    coverImageUrl: cover('ananya_movie_buff'),
    bio: 'Documentary lover. Also enjoy period dramas and anything with a strong female lead.',
    location: 'Kolkata, India',
    pronouns: 'she/her',
    website: 'https://ananyagupta.com',
  },
  {
    name: 'Karthik Menon',
    username: 'karthik_talkies',
    email: 'karthik@example.com',
    role: UserRole.USER,
    authProvider: AuthProvider.LOCAL,
    avatar: avatar('karthik_talkies'),
    coverImageUrl: cover('karthik_talkies'),
    bio: 'Old-school cinema lover. #classic #noir #hitchcock. Running a film club in Chennai.',
    location: 'Chennai, India',
  },
  {
    name: 'Deepika Iyer',
    username: 'deepika_screens',
    email: 'deepika@example.com',
    role: UserRole.USER,
    authProvider: AuthProvider.LOCAL,
    avatar: avatar('deepika_screens'),
    coverImageUrl: cover('deepika_screens'),
    bio: 'Sound design nerd. I watch movies with headphones first. #audio #dolbyatmos #imax',
    location: 'Mumbai, India',
    pronouns: 'she/her',
    socialLinks: [
      { platform: 'youtube', url: 'https://youtube.com/@deepikascreens' },
    ],
  },
  {
    name: 'Vikram Singh',
    username: 'vikram_popcorn',
    email: 'vikram@example.com',
    role: UserRole.USER,
    authProvider: AuthProvider.LOCAL,
    avatar: avatar('vikram_popcorn'),
    coverImageUrl: cover('vikram_popcorn'),
    bio: 'First day first show guy. Every Friday is movie Friday. #massala #action #entertainment',
    location: 'Lucknow, India',
  },
  {
    name: 'Meera Patel',
    username: 'meera_frames',
    email: 'meera@example.com',
    role: UserRole.USER,
    authProvider: AuthProvider.LOCAL,
    avatar: avatar('meera_frames'),
    coverImageUrl: cover('meera_frames'),
    bio: 'Cinematographer. I break down every frame. Follow for #cinematography analysis and #behindthescenes.',
    location: 'Ahmedabad, India',
    pronouns: 'she/her',
    website: 'https://meeraframes.portfolio.site',
  },
  {
    name: 'Rohan Das',
    username: 'rohan_reels',
    email: 'rohan@example.com',
    role: UserRole.USER,
    authProvider: AuthProvider.LOCAL,
    avatar: avatar('rohan_reels'),
    coverImageUrl: cover('rohan_reels'),
    bio: 'Horror movie collector. If it scares me, I watch it twice. #horror #suspense #cult',
    location: 'Guwahati, India',
  },
];
