import type { Method, Param } from '../DocComponents.js';

export interface EndpointData {
  method: Method;
  path: string;
  title: string;
  description: string;
  headers?: Param[];
  pathParams?: Param[];
  queryParams?: Param[];
  body?: string;
  response?: string;
  status?: 'Stable' | 'Beta' | 'Deprecated';
  tag?: string;
}

export const CODE_SHARE_V1_ENDPOINTS: EndpointData[] = [
  {
    method: 'POST',
    path: '/api/public/api-service',
    title: 'Create & Sign (One-step)',
    description: 'Creates a new Code Share V1 resource and returns its signed URL access credentials immediately in one step. Expects "category" to be "code-share".',
    headers: [
      { name: 'x-api-key', type: 'string', required: true, description: 'Your public API key.' },
      { name: 'x-api-secret', type: 'string', required: true, description: 'Your private API secret.' },
      { name: 'Content-Type', type: 'string', required: true, description: 'Must be application/json.' }
    ],
    body: JSON.stringify({
      category: "code-share",
      title: "My Code Snippet",
      code: "const greeting = 'Hello, V1 World!';\nconsole.log(greeting);",
      expiryMinutes: 60
    }, null, 2),
    response: JSON.stringify({
      success: true,
      message: "Resource created",
      data: {
        resourceId: "65f8c35a14d59a22fb3e6c5a",
        signedUrl: "https://yourapp.com/code-share/65f8c35a14d59a22fb3e6c5a?signature=8a2f...&expiresAt=1715527800000",
        signature: "8a2f8bdf9e2c65a0b76fd2c340b90e...a9e083c21bf",
        expiresAt: 1715527800000
      }
    }, null, 2),
    status: 'Stable',
    tag: 'code-share-v1'
  },
  {
    method: 'POST',
    path: '/api/public/api-service/signed-url',
    title: 'Generate Signed URL',
    description: 'Generates a temporary access signed URL for an existing code share snippet resource.',
    headers: [
      { name: 'x-api-key', type: 'string', required: true, description: 'Your public API key.' },
      { name: 'x-api-secret', type: 'string', required: true, description: 'Your private API secret.' },
      { name: 'Content-Type', type: 'string', required: true, description: 'Must be application/json.' }
    ],
    body: JSON.stringify({
      category: "code-share",
      resourceId: "65f8c35a14d59a22fb3e6c5a",
      expiryMinutes: 120
    }, null, 2),
    response: JSON.stringify({
      success: true,
      data: {
        signedUrl: "https://yourapp.com/code-share/65f8c35a14d59a22fb3e6c5a?signature=9c1e...&expiresAt=1715531400000",
        signature: "9c1e7a02b3e6c5a14d59a3c9ea76fd2c340b90e",
        expiresAt: 1715531400000
      }
    }, null, 2),
    status: 'Stable',
    tag: 'code-share-v1'
  },
  {
    method: 'GET',
    path: '/api/public/api-service/:category/:id',
    title: 'Guest Resource Access',
    description: 'Access a code-share resource metadata and code buffer using a valid URL signature. No API keys are required for guests.',
    pathParams: [
      { name: 'category', type: 'string', required: true, description: 'The signed service category (should be "code-share").' },
      { name: 'id', type: 'string', required: true, description: 'The resource UUID.' }
    ],
    queryParams: [
      { name: 'signature', type: 'string', required: true, description: 'The hmac-sha256 signature generated by the owner.' },
      { name: 'expiresAt', type: 'string', required: true, description: 'The unix epoch timestamp indicating when access expires.' }
    ],
    response: JSON.stringify({
      success: true,
      message: "Success",
      data: {
        _id: "65f8c35a14d59a22fb3e6c5a",
        title: "My Code Snippet",
        code: "const greeting = 'Hello, V1 World!';\nconsole.log(greeting);",
        category: "code-share",
        userId: "65f8c35a14d59a22fb3e6c55",
        createdAt: "2026-05-25T01:00:00.000Z"
      }
    }, null, 2),
    status: 'Stable',
    tag: 'code-share-v1'
  }
];

export const CODE_SHARE_V2_ENDPOINTS: EndpointData[] = [
  {
    method: 'POST',
    path: '/api/public/api-service',
    title: 'Initialize V2 Workspace',
    description: 'Creates a new multi-file project workspace repository on the server and returns signed URL credentials. Expects "category" to be "code-share-v2".',
    headers: [
      { name: 'x-api-key', type: 'string', required: true, description: 'Your public API key.' },
      { name: 'x-api-secret', type: 'string', required: true, description: 'Your private API secret.' },
      { name: 'Content-Type', type: 'string', required: true, description: 'Must be application/json.' }
    ],
    body: JSON.stringify({
      category: "code-share-v2",
      title: "My React Workspace",
      files: [
        { path: "index.html", content: "<!DOCTYPE html><html><body><div id='root'></div></body></html>" },
        { path: "src/index.js", content: "console.log('App Initialized');" }
      ],
      expiryMinutes: 1440
    }, null, 2),
    response: JSON.stringify({
      success: true,
      message: "Resource created",
      data: {
        resourceId: "65b9e0f6b3e6c5a14d59a22f",
        signedUrl: "https://yourapp.com/code-share-v2/65b9e0f6b3e6c5a14d59a22f?signature=ab76...&expiresAt=1782294902000&category=code-share-v2",
        signature: "ab76fd2c340b90e6fbfdcf9e2c65a0b76fd2c340b90e...a9e083c21bf",
        expiresAt: 1782294902000
      }
    }, null, 2),
    status: 'Stable',
    tag: 'code-share-v2'
  },
  {
    method: 'GET',
    path: '/api/public/api-service/code-share-v2/:id',
    title: 'Read Workspace Metadata',
    description: 'Retrieves project info, full file & folder registries, commits history feed, and preloads active file buffers.',
    pathParams: [
      { name: 'id', type: 'string', required: true, description: 'The V2 workspace resource ID.' }
    ],
    queryParams: [
      { name: 'action', type: 'string', required: true, description: 'Action command. Must be "v2-read".', default: 'v2-read' },
      { name: 'signature', type: 'string', required: true, description: 'The valid HMAC signature.' },
      { name: 'expiresAt', type: 'string', required: true, description: 'The expiration timestamp.' },
      { name: 'commitId', type: 'string', required: false, description: 'The specific commit ID checkout hash (optional).' }
    ],
    response: JSON.stringify({
      success: true,
      message: "Success",
      data: {
        project: {
          _id: "65b9e0f6b3e6c5a14d59a22f",
          title: "My React Workspace",
          headCommitId: "65b9e0f6b3e6c5a14d59a234"
        },
        files: [
          { path: "index.html", totalLength: 68, content: "<!DOCTYPE html><html><body><div id='root'></div></body></html>" },
          { path: "src/index.js", totalLength: 30 }
        ],
        folders: [
          { path: "src" }
        ],
        commits: [
          {
            _id: "65b9e0f6b3e6c5a14d59a234",
            message: "Initial commit",
            createdBy: "System",
            createdAt: "2026-05-25T01:00:00.000Z",
            totalChanges: 2,
            totalAdditions: 2,
            totalDeletions: 0
          }
        ]
      }
    }, null, 2),
    status: 'Stable',
    tag: 'code-share-v2'
  },
  {
    method: 'GET',
    path: '/api/public/api-service/code-share-v2/:id',
    title: 'Get Individual File Content',
    description: 'Retrieves raw text slice chunks of a workspace file at a specific commit offset. Avoids loading excessive contents at once.',
    pathParams: [
      { name: 'id', type: 'string', required: true, description: 'The V2 workspace resource ID.' }
    ],
    queryParams: [
      { name: 'action', type: 'string', required: true, description: 'Action command. Must be "v2-get-file".', default: 'v2-get-file' },
      { name: 'signature', type: 'string', required: true, description: 'The valid HMAC signature.' },
      { name: 'expiresAt', type: 'string', required: true, description: 'The expiration timestamp.' },
      { name: 'path', type: 'string', required: true, description: 'The file path to fetch.' },
      { name: 'offset', type: 'number', required: false, description: 'Text read slice offset.', default: '0' },
      { name: 'commitId', type: 'string', required: false, description: 'Specific commit hash to checkout.' }
    ],
    response: JSON.stringify({
      success: true,
      message: "Success",
      data: {
        path: "src/index.js",
        content: "console.log('App Initialized');",
        offset: 0,
        hasMore: false,
        nextOffset: 30,
        totalLength: 30
      }
    }, null, 2),
    status: 'Stable',
    tag: 'code-share-v2'
  },
  {
    method: 'POST',
    path: '/api/public/api-service/code-share-v2/:id',
    title: 'Commit Staged Changes',
    description: 'Creates a new commit in the workspace history recording staged additions, modifications, or deletions.',
    pathParams: [
      { name: 'id', type: 'string', required: true, description: 'The V2 workspace resource ID.' }
    ],
    queryParams: [
      { name: 'signature', type: 'string', required: true, description: 'The valid HMAC signature.' },
      { name: 'expiresAt', type: 'string', required: true, description: 'The expiration timestamp.' }
    ],
    body: JSON.stringify({
      action: "v2-commit",
      message: "Add CSS stylesheet and remove obsolete code",
      changes: [
        { path: "src/styles.css", type: "add", content: "body { background: #000; color: #fff; }" },
        { path: "src/obsolete.js", type: "delete" }
      ]
    }, null, 2),
    response: JSON.stringify({
      success: true,
      message: "Commit created successfully",
      data: {
        commitId: "65b9e4a2b3e6c5a14d59a3c9",
        message: "Add CSS stylesheet and remove obsolete code"
      }
    }, null, 2),
    status: 'Stable',
    tag: 'code-share-v2'
  },
  {
    method: 'GET',
    path: '/api/public/api-service/code-share-v2/:id',
    title: 'Get Commit List History',
    description: 'Fetches the full sorted commit ledger feed for a workspace.',
    pathParams: [
      { name: 'id', type: 'string', required: true, description: 'The V2 workspace resource ID.' }
    ],
    queryParams: [
      { name: 'action', type: 'string', required: true, description: 'Action command. Must be "v2-history".', default: 'v2-history' },
      { name: 'signature', type: 'string', required: true, description: 'The valid HMAC signature.' },
      { name: 'expiresAt', type: 'string', required: true, description: 'The expiration timestamp.' }
    ],
    response: JSON.stringify({
      success: true,
      message: "Success",
      data: [
        {
          _id: "65b9e4a2b3e6c5a14d59a3c9",
          message: "Add CSS stylesheet and remove obsolete code",
          createdBy: "API Key Owner",
          createdAt: "2026-05-25T01:05:00.000Z"
        }
      ]
    }, null, 2),
    status: 'Stable',
    tag: 'code-share-v2'
  },
  {
    method: 'GET',
    path: '/api/public/api-service/code-share-v2/:id',
    title: 'Get Commit Detailed Diffs',
    description: 'Retrieves granular additions, deletions, and file content diff details for a specific commit.',
    pathParams: [
      { name: 'id', type: 'string', required: true, description: 'The V2 workspace resource ID.' }
    ],
    queryParams: [
      { name: 'action', type: 'string', required: true, description: 'Action command. Must be "v2-commit-details".', default: 'v2-commit-details' },
      { name: 'signature', type: 'string', required: true, description: 'The valid HMAC signature.' },
      { name: 'expiresAt', type: 'string', required: true, description: 'The expiration timestamp.' },
      { name: 'commitId', type: 'string', required: true, description: 'The commit hash ID to inspect.' }
    ],
    response: JSON.stringify({
      success: true,
      message: "Success",
      data: {
        _id: "65b9e4a2b3e6c5a14d59a3c9",
        message: "Add CSS stylesheet and remove obsolete code",
        createdBy: "API Key Owner",
        changes: [
          {
            path: "src/styles.css",
            type: "add",
            content: "body { background: #000; color: #fff; }",
            additions: 1,
            deletions: 0
          }
        ]
      }
    }, null, 2),
    status: 'Stable',
    tag: 'code-share-v2'
  },
  {
    method: 'GET',
    path: '/api/public/api-service/code-share-v2/:id',
    title: 'Bulk Workspace Download',
    description: 'Fetches all workspace files and full content blocks in a single payload for zip archive creation.',
    pathParams: [
      { name: 'id', type: 'string', required: true, description: 'The V2 workspace resource ID.' }
    ],
    queryParams: [
      { name: 'action', type: 'string', required: true, description: 'Action command. Must be "v2-download-all".', default: 'v2-download-all' },
      { name: 'signature', type: 'string', required: true, description: 'The valid HMAC signature.' },
      { name: 'expiresAt', type: 'string', required: true, description: 'The expiration timestamp.' },
      { name: 'commitId', type: 'string', required: false, description: 'The specific commit ID checkout hash (optional).' }
    ],
    response: JSON.stringify({
      success: true,
      message: "Success",
      data: {
        projectTitle: "My React Workspace",
        files: [
          { path: "index.html", content: "<!DOCTYPE html><html><body><div id='root'></div></body></html>" },
          { path: "src/index.js", content: "console.log('App Initialized');" },
          { path: "src/styles.css", content: "body { background: #000; color: #fff; }" }
        ]
      }
    }, null, 2),
    status: 'Stable',
    tag: 'code-share-v2'
  }
];

export const CHAT_ENDPOINTS: EndpointData[] = [
  {
    method: 'POST',
    path: '/api/public/chat/conversation',
    title: 'Start Chat Conversation',
    description: 'Initializes a new support/guest chat conversation thread and returns signed URL credentials.',
    headers: [
      { name: 'x-api-key', type: 'string', required: true, description: 'Your public API key.' },
      { name: 'x-api-secret', type: 'string', required: true, description: 'Your private API secret.' },
      { name: 'Content-Type', type: 'string', required: true, description: 'Must be application/json.' }
    ],
    body: JSON.stringify({
      name: "John Doe",
      email: "johndoe@example.com",
      expiryMinutes: 60
    }, null, 2),
    response: JSON.stringify({
      success: true,
      data: {
        conversation: {
          _id: "662a5b2e6c5a14d59a22fb3e",
          name: "John Doe",
          externalUser: { name: "John Doe", email: "johndoe@example.com" }
        },
        signedUrl: "https://yourapp.com/chat/662a5b2e6c5a14d59a22fb3e?signature=abc123ef...&expiresAt=1714041600000",
        expiresAt: 1714041600000,
        existing: false
      }
    }, null, 2),
    status: 'Stable',
    tag: 'chat'
  },
  {
    method: 'POST',
    path: '/api/public/chat/conversation/signed-url',
    title: 'Refresh Guest Signed URL',
    description: 'Generates a fresh temporary guest access signed URL for an existing conversation thread.',
    headers: [
      { name: 'x-api-key', type: 'string', required: true, description: 'Your public API key.' },
      { name: 'x-api-secret', type: 'string', required: true, description: 'Your private API secret.' },
      { name: 'Content-Type', type: 'string', required: true, description: 'Must be application/json.' }
    ],
    body: JSON.stringify({
      conversationId: "662a5b2e6c5a14d59a22fb3e",
      expiryMinutes: 120
    }, null, 2),
    response: JSON.stringify({
      success: true,
      data: {
        signedUrl: "https://yourapp.com/chat/662a5b2e6c5a14d59a22fb3e?signature=xyz789ab...&expiresAt=1714043400000",
        expiresAt: 1714043400000
      }
    }, null, 2),
    status: 'Stable',
    tag: 'chat'
  },
  {
    method: 'GET',
    path: '/api/public/chat/conversation/:id',
    title: 'Get Guest Conversation Info',
    description: 'Retrieves conversation metadata and assignee details using guest signature query params.',
    pathParams: [
      { name: 'id', type: 'string', required: true, description: 'The conversation ID.' }
    ],
    queryParams: [
      { name: 'signature', type: 'string', required: true, description: 'The valid HMAC signature.' },
      { name: 'expiresAt', type: 'string', required: true, description: 'The expiration timestamp.' }
    ],
    response: JSON.stringify({
      success: true,
      conversation: {
        _id: "662a5b2e6c5a14d59a22fb3e",
        name: "John Doe",
        externalUser: {
          name: "John Doe",
          email: "johndoe@example.com"
        },
        peer: {
          _id: "662a5b2e6c5a14d59a22fb00",
          name: "Support Staff Admin",
          username: "support_admin",
          avatar: "/avatars/staff.jpg"
        },
        isActive: true,
        createdAt: "2026-05-25T01:00:00.000Z"
      }
    }, null, 2),
    status: 'Stable',
    tag: 'chat'
  },
  {
    method: 'GET',
    path: '/api/public/chat/conversation/:id/messages',
    title: 'Fetch Conversation Messages',
    description: 'Retrieves message history feed for a conversation using guest signature credentials.',
    pathParams: [
      { name: 'id', type: 'string', required: true, description: 'The conversation ID.' }
    ],
    queryParams: [
      { name: 'signature', type: 'string', required: true, description: 'The valid HMAC signature.' },
      { name: 'expiresAt', type: 'string', required: true, description: 'The expiration timestamp.' },
      { name: 'limit', type: 'number', required: false, description: 'Number of messages to load.', default: '20' },
      { name: 'latest', type: 'boolean', required: false, description: 'Set true to fetch latest messages.', default: 'true' }
    ],
    response: JSON.stringify({
      success: true,
      messages: [
        {
          _id: "662a5c0e6c5a14d59a22fc88",
          conversationId: "662a5b2e6c5a14d59a22fb3e",
          senderId: null,
          senderName: "John Doe",
          contentType: "text",
          text: "Hello support! I need help with seat reservations.",
          attachments: [],
          isSystem: false,
          createdAt: "2026-05-25T01:02:00.000Z",
          isYou: true,
          deliveryStatus: "read"
        }
      ],
      lastReadMessageId: "662a5c0e6c5a14d59a22fc88",
      hasMore: false
    }, null, 2),
    status: 'Stable',
    tag: 'chat'
  },
  {
    method: 'POST',
    path: '/api/public/chat/conversation/:id/messages',
    title: 'Send Guest Message',
    description: 'Sends a new chat message to the support thread using guest signature credentials. Expects message text directly at request root.',
    pathParams: [
      { name: 'id', type: 'string', required: true, description: 'The conversation ID.' }
    ],
    queryParams: [
      { name: 'signature', type: 'string', required: true, description: 'The valid HMAC signature.' },
      { name: 'expiresAt', type: 'string', required: true, description: 'The expiration timestamp.' }
    ],
    body: JSON.stringify({
      contentType: "text",
      text: "Here is a follow-up message about booking."
    }, null, 2),
    response: JSON.stringify({
      success: true,
      message: {
        _id: "662a5c4e6c5a14d59a22fc99",
        conversationId: "662a5b2e6c5a14d59a22fb3e",
        senderId: null,
        senderName: "John Doe",
        contentType: "text",
        text: "Here is a follow-up message about booking.",
        attachments: [],
        isSystem: false,
        createdAt: "2026-05-25T01:05:00.000Z",
        isYou: true,
        deliveryStatus: "sent"
      },
      tokens: {
        remaining: 984,
        plan: "Pro",
        cost: 1
      }
    }, null, 2),
    status: 'Stable',
    tag: 'chat'
  },
  {
    method: 'POST',
    path: '/api/public/chat/conversation/:id/messages/read',
    title: 'Mark Guest Messages Read',
    description: 'Advances the guest\'s read cursor and registers read receipts for incoming messages.',
    pathParams: [
      { name: 'id', type: 'string', required: true, description: 'The conversation ID.' }
    ],
    queryParams: [
      { name: 'signature', type: 'string', required: true, description: 'The valid HMAC signature.' },
      { name: 'expiresAt', type: 'string', required: true, description: 'The expiration timestamp.' }
    ],
    body: JSON.stringify({
      messageIds: ["662a5c0e6c5a14d59a22fc88"]
    }, null, 2),
    response: JSON.stringify({
      success: true,
      markedIds: ["662a5c0e6c5a14d59a22fc88"]
    }, null, 2),
    status: 'Stable',
    tag: 'chat'
  },
  {
    method: 'GET',
    path: '/api/public/chat/conversation/:id/subscription',
    title: 'Get Guest Subscription Quota',
    description: 'Fetches the remaining billing tokens quota for the API key owner of the conversation.',
    pathParams: [
      { name: 'id', type: 'string', required: true, description: 'The conversation ID.' }
    ],
    queryParams: [
      { name: 'signature', type: 'string', required: true, description: 'The valid HMAC signature.' },
      { name: 'expiresAt', type: 'string', required: true, description: 'The expiration timestamp.' }
    ],
    response: JSON.stringify({
      success: true,
      subscription: {
        plan: "Pro",
        billingCycle: "Monthly",
        status: "active",
        startsAt: "2026-05-01T00:00:00.000Z",
        expiresAt: "2026-06-01T00:00:00.000Z",
        customMonthlyLimit: null,
        customDurationMonths: null,
        purchasesCount: 1
      },
      remaining: 984
    }, null, 2),
    status: 'Stable',
    tag: 'chat'
  }
];
