import React from 'react';
import { MessageSquare, Shield, Clock } from 'lucide-react';
import { EndpointCard } from './EndpointCard.js';
import { DocSection } from './DocComponents.js';

export const GuestApi = () => {
  return (
    <DocSection title="Guest API" icon={MessageSquare} id="guest-api">
      <div className="bg-purple-500/5 border border-purple-500/10 p-6 md:p-8 rounded-[2.5rem] space-y-6 mb-12">
        <div className="flex items-center gap-3 text-purple-400">
          <Shield size={18} />
          <h4 className="text-sm font-black uppercase tracking-widest text-[11px]">Signature Verification</h4>
        </div>
        <div className="space-y-4">
          <p className="text-sm text-gray-400 leading-relaxed">
            The Guest API represents the public-facing interface for your end-users. It does not require API keys. 
            Instead, every request is authorized via a <span className="text-purple-300 font-bold">Cryptographic Signature</span> generated by the Management API.
          </p>
          <div className="flex items-center gap-3 text-[10px] text-gray-500 bg-white/5 p-3 rounded-xl border border-white/5">
            <Clock size={14} className="text-purple-400" />
            <span>Signatures are time-bound and automatically expire based on the <code className="text-purple-300">expiresAt</code> field.</span>
          </div>
        </div>
      </div>

      <div className="space-y-12">
        <EndpointCard
          method="GET"
          path="/public/chat/conversation/:id"
          description="Fetch metadata for a conversation, including info about the assigned support agent."
          pathParams={[
            { name: 'id', type: 'string', required: true, description: 'The conversation ID.' }
          ]}
          queryParams={[
            { name: 'signature', type: 'string', required: true, description: 'HMAC signature for authorization.' },
            { name: 'expiresAt', type: 'number', required: true, description: 'Unix timestamp when the signature/session expires.' },
          ]}
          response={JSON.stringify({
            success: true,
            conversation: {
              _id: "662a...",
              peer: { name: "Support Agent", username: "agent_01", avatar: "..." }
            }
          }, null, 2)}
        />

        <EndpointCard
          method="GET"
          path="/public/chat/conversation/:id/messages"
          description="Retrieve message history for the conversation with cursor-based pagination."
          pathParams={[
            { name: 'id', type: 'string', required: true, description: 'The conversation ID.' }
          ]}
          queryParams={[
            { name: 'signature', type: 'string', required: true, description: 'HMAC signature for authorization.' },
            { name: 'expiresAt', type: 'number', required: true, description: 'Unix timestamp (ms).' },
            { name: 'limit', type: 'number', required: false, description: 'Number of messages to return.', default: '20' },
            { name: 'before', type: 'string', required: false, description: 'Message ID cursor for older messages.' },
            { name: 'after', type: 'string', required: false, description: 'Message ID cursor for newer messages.' },
          ]}
          response={JSON.stringify({
            success: true,
            messages: [{ _id: "msg_01", text: "Hello!", senderName: "Support Agent", isYou: false }],
            hasOlder: false,
            hasNewer: false
          }, null, 2)}
        />

        <EndpointCard
          method="POST"
          path="/public/chat/conversation/:id/messages"
          description="Submit a new message or interaction to the conversation thread."
          pathParams={[
            { name: 'id', type: 'string', required: true, description: 'The conversation ID.' }
          ]}
          queryParams={[
            { name: 'signature', type: 'string', required: true, description: 'HMAC signature for authorization.' },
            { name: 'expiresAt', type: 'number', required: true, description: 'Unix timestamp (ms).' },
          ]}
          body={JSON.stringify({ 
            text: "Thanks for the help!", 
            contentType: "text" 
          }, null, 2)}
          response={JSON.stringify({
            success: true,
            message: { _id: "msg_99", text: "Thanks for the help!", deliveryStatus: "sent", isYou: true }
          }, null, 2)}
        />
      </div>
    </DocSection>
  );
};
